
import java.awt.Component;
import java.awt.ComponentOrientation;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lia
 */
public class CampoMinadoView extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form CampoMinadoView
     */
    public CampoMinadoView() {
        initComponents();
        
        setLocationRelativeTo(null);
        setSize(400,400);
        
        ImageIcon i = new ImageIcon("happypqn.png");
        btnReinicia.setIcon(i);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        btnReinicia = new javax.swing.JButton();
        jogoPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnReinicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(btnReinicia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReinicia)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(menuPanel, java.awt.BorderLayout.PAGE_START);

        jogoPanel.setLayout(new java.awt.GridLayout(9, 9));
        getContentPane().add(jogoPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReiniciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciaActionPerformed
        ImageIcon i = new ImageIcon("deadpqn.png");
        btnReinicia.setIcon(i);
        
        for (int j=0;j<81;j++){
            ImageIcon icon = new ImageIcon("squarepqn3.png");
            
            JButton button = new JButton();
            button.setName("btn"+j);
            button.setActionCommand("btnCampoMinado");
            button.addActionListener(this);
//            button.setBorderPainted(false); 
            button.setContentAreaFilled(false);
//            button.setFocusPainted(false); 
//            button.setOpaque(false);
            button.setIcon(icon);
            
            
           
//            y.setIcon(x);
//            y.setBorder(null);
//            y.setFocusPainted(false);
//            y.setContentAreaFilled(false);
            Component x = jogoPanel.add(button, j);
        }
        setSize(450,450);
        setSize(400,400);

    }//GEN-LAST:event_btnReiniciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CampoMinadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CampoMinadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CampoMinadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CampoMinadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CampoMinadoView().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReinicia;
    private javax.swing.JPanel jogoPanel;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        String cmd = e.getActionCommand();
        
        if (cmd.equals("btnCampoMinado")){
            javax.swing.JButton button = (javax.swing.JButton) e.getSource();
            
            System.out.println(button.getName().substring(3));
            JOptionPane.showMessageDialog(this, "Você clicou no botão " + button.getName(), "Informação", JOptionPane.INFORMATION_MESSAGE);
            JLabel label =new JLabel();
            label.setName("lbl"+button.getName().substring(3).trim());
            label.setSize(button.getSize());
            Component x = jogoPanel.getComponent(Integer.parseInt(button.getName().substring(3).trim()));

            System.out.println(x.getName());
            
            Component[] componentes = jogoPanel.getComponents();
            
            jogoPanel.removeAll();
            
            jogoPanel.repaint();
            jogoPanel.revalidate();
            
            for (Component componente : componentes){
                if (componente.getName().equals(button.getName())){
                    jogoPanel.add(label);
                }else{
                    jogoPanel.add(componente);
                }
            }
            
            jogoPanel.repaint();
            jogoPanel.revalidate();
        }
    }
}
