/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ufpr.sistemabanco.view.menuinicial;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import org.ufpr.sistemabanco.controller.ClienteController;
import org.ufpr.sistemabanco.controller.ContaController;
import org.ufpr.sistemabanco.controller.VinculaContaController;
import org.ufpr.sistemabanco.model.dao.ClienteDao;
import org.ufpr.sistemabanco.model.dao.ContaDao;
import org.ufpr.sistemabanco.view.cliente.JanelaClienteView;
import org.ufpr.sistemabanco.view.manipulaconta.JanelaManipulaContaView;
import org.ufpr.sistemabanco.view.vinculaconta.JanelaVinculaContaView;

/**
 *
 * @author Lia
 */
public class BotoesMenuView extends javax.swing.JPanel implements ActionListener{

    /**
     * Creates new form BotoesMenuView
     */
    public BotoesMenuView() {
        initComponents();
        
        btnCliente.addActionListener(this);
        btnVinculaConta.addActionListener(this);
        btnConta.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCliente = new javax.swing.JButton();
        btnVinculaConta = new javax.swing.JButton();
        btnConta = new javax.swing.JButton();

        btnCliente.setText("Gerenciar Clientes");
        btnCliente.setActionCommand("abrirClienteView");

        btnVinculaConta.setText("Vincular Conta");
        btnVinculaConta.setActionCommand("abrirVinculaContaClienteView");

        btnConta.setText("Manipular Conta");
        btnConta.setActionCommand("abrirContaView");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVinculaConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btnVinculaConta)
                .addGap(73, 73, 73)
                .addComponent(btnConta)
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnConta;
    private javax.swing.JButton btnVinculaConta;
    // End of variables declaration//GEN-END:variables

    private JanelaMenuView janelaMenuView;

    public void setJanelaMenuView(JanelaMenuView janelaMenuView) {
        this.janelaMenuView = janelaMenuView;
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        String cmd = e.getActionCommand();
        
        if (cmd.equals("abrirClienteView")){
            JanelaClienteView janelaClienteView = new JanelaClienteView();
            ClienteDao clienteDao = new ClienteDao();
            
            ClienteController controller = new ClienteController(janelaClienteView, clienteDao);
            
            janelaMenuView.dispose();
        }else if (cmd.equals("abrirVinculaContaClienteView")){
            JanelaVinculaContaView janelaVinculaContaView = new JanelaVinculaContaView();
            ClienteDao clienteDao = new ClienteDao();
            ContaDao contaDao = new ContaDao();
            
            VinculaContaController clienteController = new VinculaContaController(janelaVinculaContaView, clienteDao, contaDao);
            
            janelaMenuView.dispose();

        }else if (cmd.equals("abrirContaView")){
            JanelaManipulaContaView janelaManipulaContaView = new JanelaManipulaContaView();
            ClienteDao clienteDao = new ClienteDao();
            ContaDao contaDao = new ContaDao();
            
            ContaController clienteController = new ContaController(janelaManipulaContaView, clienteDao, contaDao);
            
            janelaMenuView.dispose();
        }
        
    }
}
