/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ufpr.lpooii.view.menu;

import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import org.ufpr.lpooii.controller.AutorController;
import org.ufpr.lpooii.controller.LivroController;
import org.ufpr.lpooii.model.dao.AutorDAO;
import org.ufpr.lpooii.model.dao.LivroDAO;
import org.ufpr.lpooii.view.autor.JanelaAutorView;
import org.ufpr.lpooii.view.livro.JanelaLivroView;

/**
 *
 * @author Lia
 */
public class MenuView extends javax.swing.JPanel implements ActionListener{

    private JanelaMenuView janelaMenuView;
    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        
        btnAutor.addActionListener(this);
        btnLivro.addActionListener(this);
    }

    public void setJanelaMenuView(JanelaMenuView janelaMenuView) {
        this.janelaMenuView = janelaMenuView;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAutor = new javax.swing.JButton();
        btnLivro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btnAutor.setText("Autor");
        btnAutor.setActionCommand("abrirAutorView");

        btnLivro.setText("Livro");
        btnLivro.setActionCommand("abrirLivroView");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Menu inicial");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(176, 176, 176))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutor;
    private javax.swing.JButton btnLivro;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        String cmd = e.getActionCommand();
        System.out.println(cmd);
        
        if (cmd.equals("abrirAutorView")){
            JanelaAutorView view = new JanelaAutorView();
            AutorDAO autorDao = new AutorDAO();

//            Frame[] f = JanelaMenuView.getFrames();
//            for (Frame f1 : f) {
//                f1.dispose();
//            }
            
            AutorController controller = new AutorController(view, autorDao);
            janelaMenuView.dispose();
//            
//            JanelaAutorView janelaAutorView = new JanelaAutorView();
//            janelaAutorView.setVisible(true);

            
        }else if (cmd.equals("abrirLivroView")){
           JanelaLivroView view = new JanelaLivroView();
           LivroDAO livroDao = new LivroDAO();
           
           LivroController controller = new LivroController(view, livroDao);
           janelaMenuView.dispose();
        }
    }
}
