/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ufpr.sistemabanco.view.cliente;

import java.util.List;
import javax.swing.JOptionPane;
import org.ufpr.sistemabanco.controller.ClienteController;
import org.ufpr.sistemabanco.model.Cliente;

/**
 *
 * @author Lia
 */
public class JanelaClienteView extends javax.swing.JFrame {

    /**
     * Creates new form JanelaClienteView
     */
    public JanelaClienteView() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoesClienteView = new org.ufpr.sistemabanco.view.cliente.botoesClienteView();
        tabelaClienteView = new org.ufpr.sistemabanco.view.cliente.TabelaClienteView();
        formularioCliente = new org.ufpr.sistemabanco.view.cliente.FormularioCliente();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formularioCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabelaClienteView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botoesClienteView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(botoesClienteView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelaClienteView, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formularioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.ufpr.sistemabanco.view.cliente.botoesClienteView botoesClienteView;
    private org.ufpr.sistemabanco.view.cliente.FormularioCliente formularioCliente;
    private org.ufpr.sistemabanco.view.cliente.TabelaClienteView tabelaClienteView;
    // End of variables declaration//GEN-END:variables

    private ClienteTableModel clienteTableModel = new ClienteTableModel();
    
    public void setController(ClienteController controller) {
        botoesClienteView.setController(controller);
    }

    public void initView() {
         java.awt.EventQueue.invokeLater(() -> this.setVisible(true));
         
         tabelaClienteView.getTabelaCliente().setModel(clienteTableModel);
    }

    public Cliente getClienteFormulario() {
      String nome = formularioCliente.getNomeCampo().getText();
      String sobrenome = formularioCliente.getSobrenomeCampo().getText();
      String rg = formularioCliente.getRgCampo().getText();
      String cpf = formularioCliente.getCpfCampo().getText();
      String endereco = formularioCliente.getEnderecoCampo().getText();

      return new Cliente(nome, sobrenome, rg, cpf, endereco);
    }

    public void inserirClienteView(Cliente cliente) {
        clienteTableModel.adicionaCliente(cliente);
    }

    public void mostrarListaClientes(List<Cliente> lista) {
        clienteTableModel.setListaCliente(lista);
    }
    
        public void apresentaInfo(String info) {
        JOptionPane.showMessageDialog(null, info + "\n", "Informação", JOptionPane.INFORMATION_MESSAGE);
    }

    public void apresentaErro(String erro) {
        JOptionPane.showMessageDialog(null, erro + "\n", "Erro", JOptionPane.ERROR_MESSAGE);
    }
}
