/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ufpr.sistemabanco.view.vinculaconta;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.ufpr.sistemabanco.controller.VinculaContaController;
import org.ufpr.sistemabanco.view.menuinicial.JanelaMenuView;

/**
 *
 * @author Lia
 */
public class BotaoNumeroConta extends javax.swing.JPanel {

    /**
     * Creates new form BotaoNumeroConta
     */
    public BotaoNumeroConta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCriarConta = new javax.swing.JToggleButton();
        NumContaLabel = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();

        btnCriarConta.setText("Gerar Conta");

        NumContaLabel.setText("Numero:");

        btnVoltar.setText("< Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCriarConta)
                .addGap(18, 18, 18)
                .addComponent(NumContaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriarConta)
                    .addComponent(NumContaLabel)
                    .addComponent(btnVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        JanelaMenuView menuView = new JanelaMenuView();
        
        menuView.show();
        view.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NumContaLabel;
    private javax.swing.JToggleButton btnCriarConta;
    private javax.swing.JButton btnVoltar;
    // End of variables declaration//GEN-END:variables

    private JanelaVinculaContaView view;
    
    void setController(VinculaContaController controller) {
        
        this.btnCriarConta.addActionListener(new ActionListener() {
          @Override
          public void actionPerformed(ActionEvent e) {
              if (view.getPanelAtivo().equals("corrente")){
                controller.criarContaCorrente();
              } else if (view.getPanelAtivo().equals("investimento")){
                controller.criarContaInvestimento();
              } else {
                JOptionPane.showMessageDialog(null, "Selecione o tipo da conta." + "\n", "Erro", JOptionPane.ERROR_MESSAGE);
              }
          }
      });
    }

    void setView(JanelaVinculaContaView view) {
        this.view = view;
    }

    public void setNumContaLabel(JLabel NumContaLabel) {
        this.NumContaLabel = NumContaLabel;
    }

    public JLabel getNumContaLabel() {
        return NumContaLabel;
    }
    
     
}
