/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ufpr.sistemabanco.view.vinculaconta;

import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.util.List;
import javax.swing.JOptionPane;
import org.ufpr.sistemabanco.controller.VinculaContaController;
import org.ufpr.sistemabanco.model.Cliente;

/**
 *
 * @author Lia
 */
public class JanelaVinculaContaView extends javax.swing.JFrame {

    /**
     * Creates new form JanelaVinculaContaView
     */
    public JanelaVinculaContaView() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscaClienteView = new org.ufpr.sistemabanco.view.vinculaconta.BuscaClienteView();
        tabelaClienteView = new org.ufpr.sistemabanco.view.vinculaconta.TabelaClienteView();
        tipoContaView1 = new org.ufpr.sistemabanco.view.vinculaconta.TipoContaView();
        panelConta = new javax.swing.JPanel();
        panelDefault = new javax.swing.JPanel();
        panelContaInvestimento = new javax.swing.JPanel();
        montanteMinCampo = new javax.swing.JTextField();
        depositoInicialLabel = new javax.swing.JLabel();
        depositoInicialCampo = new javax.swing.JTextField();
        depositoMinLabel = new javax.swing.JLabel();
        depositoMinCampo = new javax.swing.JTextField();
        montanteMinLabel = new javax.swing.JLabel();
        panelContaCorrente = new javax.swing.JPanel();
        depositoLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        botaoNumeroConta1 = new org.ufpr.sistemabanco.view.vinculaconta.BotaoNumeroConta();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelConta.setToolTipText("");
        panelConta.setLayout(new java.awt.CardLayout());

        panelDefault.setForeground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout panelDefaultLayout = new javax.swing.GroupLayout(panelDefault);
        panelDefault.setLayout(panelDefaultLayout);
        panelDefaultLayout.setHorizontalGroup(
            panelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelDefaultLayout.setVerticalGroup(
            panelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        panelConta.add(panelDefault, "card2");

        panelContaInvestimento.setForeground(new java.awt.Color(153, 255, 153));

        depositoInicialLabel.setText("Deposito inicial:");

        depositoMinLabel.setText("Deposito mínimo:");

        montanteMinLabel.setText("Montante mínimo:");

        javax.swing.GroupLayout panelContaInvestimentoLayout = new javax.swing.GroupLayout(panelContaInvestimento);
        panelContaInvestimento.setLayout(panelContaInvestimentoLayout);
        panelContaInvestimentoLayout.setHorizontalGroup(
            panelContaInvestimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContaInvestimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContaInvestimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelContaInvestimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(depositoInicialLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelContaInvestimentoLayout.createSequentialGroup()
                            .addGroup(panelContaInvestimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContaInvestimentoLayout.createSequentialGroup()
                                    .addComponent(depositoMinLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(panelContaInvestimentoLayout.createSequentialGroup()
                                    .addComponent(montanteMinLabel)
                                    .addGap(8, 8, 8)))
                            .addGroup(panelContaInvestimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(montanteMinCampo)
                                .addComponent(depositoMinCampo, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))))
                    .addComponent(depositoInicialCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        panelContaInvestimentoLayout.setVerticalGroup(
            panelContaInvestimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContaInvestimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContaInvestimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(montanteMinLabel)
                    .addComponent(montanteMinCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContaInvestimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositoMinLabel)
                    .addComponent(depositoMinCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContaInvestimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositoInicialLabel)
                    .addComponent(depositoInicialCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelConta.add(panelContaInvestimento, "card3");

        panelContaCorrente.setForeground(new java.awt.Color(153, 255, 153));

        depositoLabel.setText("Deposito:");

        jLabel1.setText("Limite:");

        javax.swing.GroupLayout panelContaCorrenteLayout = new javax.swing.GroupLayout(panelContaCorrente);
        panelContaCorrente.setLayout(panelContaCorrenteLayout);
        panelContaCorrenteLayout.setHorizontalGroup(
            panelContaCorrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContaCorrenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContaCorrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(depositoLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(panelContaCorrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(jTextField2))
                .addGap(52, 52, 52))
        );
        panelContaCorrenteLayout.setVerticalGroup(
            panelContaCorrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContaCorrenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContaCorrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositoLabel)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContaCorrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        panelConta.add(panelContaCorrente, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscaClienteView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabelaClienteView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tipoContaView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoNumeroConta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buscaClienteView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelaClienteView, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(tipoContaView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelConta, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoNumeroConta1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.ufpr.sistemabanco.view.vinculaconta.BotaoNumeroConta botaoNumeroConta1;
    private org.ufpr.sistemabanco.view.vinculaconta.BuscaClienteView buscaClienteView;
    private javax.swing.JTextField depositoInicialCampo;
    private javax.swing.JLabel depositoInicialLabel;
    private javax.swing.JLabel depositoLabel;
    private javax.swing.JTextField depositoMinCampo;
    private javax.swing.JLabel depositoMinLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField montanteMinCampo;
    private javax.swing.JLabel montanteMinLabel;
    private javax.swing.JPanel panelConta;
    private javax.swing.JPanel panelContaCorrente;
    private javax.swing.JPanel panelContaInvestimento;
    private javax.swing.JPanel panelDefault;
    private org.ufpr.sistemabanco.view.vinculaconta.TabelaClienteView tabelaClienteView;
    private org.ufpr.sistemabanco.view.vinculaconta.TipoContaView tipoContaView1;
    // End of variables declaration//GEN-END:variables

    private ClienteTableModel clienteTableModel = new ClienteTableModel();
    private int linhaClicada = -1;
    private String panelAtivo = "default";

    public void setController(VinculaContaController controller) {
        buscaClienteView.setController(controller);
        tipoContaView1.setView(this);
        controller.listarCliente();
        
    }
    
    public void mudarPanelCorrente(){
        System.out.println(panelAtivo);
        panelConta.removeAll();
        panelConta.repaint();
        panelConta.revalidate();
        
        panelConta.add(panelContaCorrente);
        panelConta.repaint();
        panelConta.revalidate();
        panelAtivo = "corrente";
    }
    
    public void mudarPanelInvestimento(){
        System.out.println(panelAtivo);
        panelConta.removeAll();
        panelConta.repaint();
        panelConta.revalidate();
        
        panelConta.add(panelContaInvestimento);
        panelConta.repaint();
        panelConta.revalidate();
         panelAtivo = "investimento";
    }
    
    public Cliente getClienteParaVincular(){
        linhaClicada = tabelaClienteView.getTabelaCliente().getSelectedRow();
        Cliente cliente = clienteTableModel.getCliente(linhaClicada);

        return cliente;
      }

    public void initView() {
        java.awt.EventQueue.invokeLater(() -> this.setVisible(true));
        
        tabelaClienteView.getTabelaCliente().setModel(clienteTableModel);
    }

    public void mostrarListaClientes(List<Cliente> lista) {
        clienteTableModel.setListaCliente(lista);
    }

    public void apresentaInfo(String info) {
        JOptionPane.showMessageDialog(null, info + "\n", "Informação", JOptionPane.INFORMATION_MESSAGE);
    }

    public void apresentaErro(String erro) {
        JOptionPane.showMessageDialog(null, erro + "\n", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    public String getBusca() {
        return buscaClienteView.getBuscaCampo().getText();
    }
}
