/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ufpr.sistemabanco.view.manipulaconta;

import org.ufpr.sistemabanco.view.cliente.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import org.ufpr.sistemabanco.controller.ClienteController;
import org.ufpr.sistemabanco.controller.ContaController;

/**
 *
 * @author Lia
 */
public class botoesOperacaoContaView extends javax.swing.JPanel {

    /**
     * Creates new form botoesClienteView
     */
    public botoesOperacaoContaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDepositar = new javax.swing.JButton();
        btnSaldo = new javax.swing.JButton();
        btnRemunerar = new javax.swing.JButton();
        btnSacar = new javax.swing.JButton();

        btnDepositar.setText("Depositar");

        btnSaldo.setText("Ver Saldo");

        btnRemunerar.setText("Remunerar");

        btnSacar.setText("Sacar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDepositar)
                .addGap(18, 18, 18)
                .addComponent(btnSaldo)
                .addGap(18, 18, 18)
                .addComponent(btnRemunerar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacar)
                    .addComponent(btnDepositar)
                    .addComponent(btnSaldo)
                    .addComponent(btnRemunerar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnRemunerar;
    private javax.swing.JButton btnSacar;
    private javax.swing.JButton btnSaldo;
    // End of variables declaration//GEN-END:variables

    void setController(ContaController controller) {
        this.btnSacar.addActionListener(e -> controller.sacar());
      this.btnDepositar.addActionListener(e -> controller.depositar());
      this.btnSaldo.addActionListener(e -> controller.saldo());
      this.btnRemunerar.addActionListener(e -> controller.remunerar());
    }
}
