
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lia
 */
public class CalculadoraFrame extends javax.swing.JFrame implements ActionListener {

    enum EstadoCalculadora {
        INICIAL, IGNORADO, ENTRADA1, OPERADOR, ENTRADA2, CALCULANDO
    }
    
    private EstadoCalculadora estadoCalc = EstadoCalculadora.INICIAL;
    private int num1=0, num2=0;
    private char sinal='+', sinalNum1='+', sinalNum2='+';
    
    /**
     * Creates new form CalculadoraFrame
     */
    public CalculadoraFrame() {

//            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        
        initComponents();
        
        btn0.addActionListener(this);
        btn1.addActionListener(this);
        btn2.addActionListener(this);
        btn3.addActionListener(this);
        btn4.addActionListener(this);
        btn5.addActionListener(this);
        btn6.addActionListener(this);
        btn7.addActionListener(this);
        btn8.addActionListener(this);
        btn9.addActionListener(this);
        
        btnIgual.addActionListener(this);
        btnC.addActionListener(this);
        btnDivide.addActionListener(this);
        btnMultiplica.addActionListener(this);
        btnDiminui.addActionListener(this);
        btnSoma.addActionListener(this);
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        PanelDisplay = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextPane();
        PanelBotoes = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnSoma = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnDiminui = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnMultiplica = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(display);

        javax.swing.GroupLayout PanelDisplayLayout = new javax.swing.GroupLayout(PanelDisplay);
        PanelDisplay.setLayout(PanelDisplayLayout);
        PanelDisplayLayout.setHorizontalGroup(
            PanelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDisplayLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        PanelDisplayLayout.setVerticalGroup(
            PanelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDisplayLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(PanelDisplay, java.awt.BorderLayout.PAGE_START);

        PanelBotoes.setLayout(new java.awt.GridLayout(4, 4, 2, 2));

        btn7.setText("7");
        btn7.setActionCommand("btnNumero");
        PanelBotoes.add(btn7);

        btn8.setText("8");
        btn8.setActionCommand("btnNumero");
        PanelBotoes.add(btn8);

        btn9.setText("9");
        btn9.setActionCommand("btnNumero");
        PanelBotoes.add(btn9);

        btnSoma.setText("+");
        btnSoma.setActionCommand("btnOperacao");
        PanelBotoes.add(btnSoma);

        btn4.setText("4");
        btn4.setActionCommand("btnNumero");
        PanelBotoes.add(btn4);

        btn5.setText("5");
        btn5.setActionCommand("btnNumero");
        PanelBotoes.add(btn5);

        btn6.setText("6");
        btn6.setActionCommand("btnNumero");
        PanelBotoes.add(btn6);

        btnDiminui.setText("-");
        btnDiminui.setActionCommand("btnOperacao");
        PanelBotoes.add(btnDiminui);

        btn1.setText("1");
        btn1.setActionCommand("btnNumero");
        PanelBotoes.add(btn1);

        btn2.setText("2");
        btn2.setActionCommand("btnNumero");
        PanelBotoes.add(btn2);

        btn3.setText("3");
        btn3.setActionCommand("btnNumero");
        PanelBotoes.add(btn3);

        btnMultiplica.setText("x");
        btnMultiplica.setActionCommand("btnOperacao");
        PanelBotoes.add(btnMultiplica);

        btn0.setText("0");
        btn0.setActionCommand("btnNumero");
        PanelBotoes.add(btn0);

        btnIgual.setText("=");
        btnIgual.setActionCommand("btnResultado");
        PanelBotoes.add(btnIgual);

        btnC.setText("C");
        btnC.setActionCommand("btnLimpar");
        PanelBotoes.add(btnC);

        btnDivide.setText("/");
        btnDivide.setActionCommand("btnOperacao");
        PanelBotoes.add(btnDivide);

        getContentPane().add(PanelBotoes, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBotoes;
    private javax.swing.JPanel PanelDisplay;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnDiminui;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMultiplica;
    private javax.swing.JButton btnSoma;
    private javax.swing.JTextPane display;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        
        
        String cmd = e.getActionCommand();
        
        if ("btnNumero".equals(cmd)){
            javax.swing.JButton j = (javax.swing.JButton) e.getSource();
            String digito = j.getText();
            
            if (estadoCalc.equals(EstadoCalculadora.INICIAL)){
               num1=Integer.parseInt(digito);
               estadoCalc = estadoCalc.ENTRADA1;
               display.setText(display.getText()+String.valueOf(num1));
            }else if (estadoCalc.equals(EstadoCalculadora.ENTRADA1)){
               String StrN1 = String.valueOf(num1);
               num1=Integer.parseInt(StrN1+digito);
               display.setText(display.getText()+digito);
            }else if (estadoCalc.equals(EstadoCalculadora.OPERADOR)){
               num2=Integer.parseInt(digito);
               estadoCalc = estadoCalc.ENTRADA2;
               display.setText(display.getText()+String.valueOf(num2));
            }else if (estadoCalc.equals(EstadoCalculadora.ENTRADA2)){
               String StrN2 = String.valueOf(num2);
               num2=Integer.parseInt(StrN2+digito);
               display.setText(display.getText()+digito);
            }
            
//            JOptionPane.showMessageDialog(this, "Você clicou em um botão numérico: "+j.getText(), "Informação", JOptionPane.INFORMATION_MESSAGE);
        }else if ("btnOperacao".equals(cmd)){
            javax.swing.JButton j = (javax.swing.JButton) e.getSource();
            String digito = j.getText();
            
            if (estadoCalc.equals(EstadoCalculadora.INICIAL)){//para o sinal
                sinalNum1=digito.charAt(0);
                display.setText(String.valueOf(sinalNum1));
            }
             if (estadoCalc.equals(EstadoCalculadora.ENTRADA1)){
               sinal=digito.charAt(0);
               estadoCalc = estadoCalc.OPERADOR;
               display.setText(display.getText()+sinal);
            }else if (estadoCalc.equals(EstadoCalculadora.OPERADOR)){
                if (digito.equals("+")||digito.equals("-")){
                    sinalNum2=digito.charAt(0);
                    if (display.getText().charAt(display.getText().length()-2)=='/'||display.getText().charAt(display.getText().length()-2)=='x'||display.getText().charAt(display.getText().length()-2)=='+'||display.getText().charAt(display.getText().length()-2)=='-') {
                        display.setText(display.getText().substring(0, display.getText().length()-1)+sinal);
                    }else{
                        display.setText(display.getText()+digito);
                    }
                }
            }else if (estadoCalc.equals(EstadoCalculadora.ENTRADA2)){
               int resposta = calcula();
               num1=resposta;
               sinal=digito.charAt(0);
               display.setText(String.valueOf(num1)+sinal);
               estadoCalc = estadoCalc.OPERADOR;
            }
            
//            JOptionPane.showMessageDialog(this, "Você clicou em um botão de operação", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }else if ("btnLimpar".equals(cmd)){
            estadoCalc = estadoCalc.INICIAL;
            num1=0;
            num2=0;
            sinal='+';
            display.setText("");
            sinalNum1='+';
            sinalNum2='+';
//            JOptionPane.showMessageDialog(this, "Você clicou no botão de limpar", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }else if ("btnResultado".equals(cmd)){
            if (estadoCalc.equals(EstadoCalculadora.ENTRADA2)){
                int resposta = calcula();
                display.setText(String.valueOf(resposta));
                estadoCalc = estadoCalc.CALCULANDO;
//                JOptionPane.showMessageDialog(this, "O resultado é: "+resposta, "Informação", JOptionPane.INFORMATION_MESSAGE);
            }
        }    
    }
    
    private int calcula(){
        int resposta=0;
        
        String StrN = String.valueOf(sinalNum1);
        num1=Integer.parseInt(StrN+num1);
        
        StrN = String.valueOf(sinalNum2);
        num2=Integer.parseInt(StrN+num2);
        
        if(sinal=='+'){
            resposta = num1+num2;
        }else if(sinal=='-'){
            resposta = num1-num2;
        }else if(sinal=='x'){
            resposta = num1*num2;
        }else {
            resposta = num1/num2;
        }
        return resposta;
    }
}
