
import java.awt.image.BufferedImage;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lia Alflen
 */
public class VisualizadorImagemJFrame extends javax.swing.JFrame{   
    /**
     * Creates new form VisualizadorImagemJFrame
     */
    public VisualizadorImagemJFrame() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        AbrirAction abrirAction = new AbrirAction(this);
        jMenuItemAbrir.setAction(abrirAction);
        abrirBtn.setAction(abrirAction);
        intFrameImage.setVisible(false);
    }

    public void setIntFrameImage(BufferedImage imagem) {
        panelImagem.setImg(imagem);
        panelImagem.repaint();
        this.intFrameImage.setVisible(true);
        
        pack();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanel = new javax.swing.JDesktopPane();
        barraFerramentas = new javax.swing.JToolBar();
        abrirBtn = new javax.swing.JButton();
        intFrameImage = new javax.swing.JInternalFrame();
        panelImagem = new PanelImagem();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuAbrir = new javax.swing.JMenu();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPanel.setBackground(new java.awt.Color(240, 240, 240));

        barraFerramentas.setRollover(true);

        abrirBtn.setText("Abrir");
        abrirBtn.setFocusable(false);
        abrirBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        abrirBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraFerramentas.add(abrirBtn);

        intFrameImage.setVisible(true);

        javax.swing.GroupLayout panelImagemLayout = new javax.swing.GroupLayout(panelImagem);
        panelImagem.setLayout(panelImagemLayout);
        panelImagemLayout.setHorizontalGroup(
            panelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );
        panelImagemLayout.setVerticalGroup(
            panelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout intFrameImageLayout = new javax.swing.GroupLayout(intFrameImage.getContentPane());
        intFrameImage.getContentPane().setLayout(intFrameImageLayout);
        intFrameImageLayout.setHorizontalGroup(
            intFrameImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        intFrameImageLayout.setVerticalGroup(
            intFrameImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPanel.setLayer(barraFerramentas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanel.setLayer(intFrameImage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPanelLayout = new javax.swing.GroupLayout(jDesktopPanel);
        jDesktopPanel.setLayout(jDesktopPanelLayout);
        jDesktopPanelLayout.setHorizontalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(intFrameImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
            .addComponent(barraFerramentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPanelLayout.setVerticalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPanelLayout.createSequentialGroup()
                .addComponent(barraFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(intFrameImage)
                .addGap(43, 43, 43))
        );

        getContentPane().add(jDesktopPanel, java.awt.BorderLayout.CENTER);

        jMenuAbrir.setText("Arquivo");
        jMenuAbrir.setActionCommand("abrirInternalFrame");

        jMenuItemAbrir.setText("Abrir");
        jMenuAbrir.add(jMenuItemAbrir);

        jMenuBar.add(jMenuAbrir);

        jMenu2.setText("Edit");
        jMenuBar.add(jMenu2);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     * @author Lia Alflen
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizadorImagemJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizadorImagemJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizadorImagemJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizadorImagemJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizadorImagemJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirBtn;
    private javax.swing.JToolBar barraFerramentas;
    private javax.swing.JInternalFrame intFrameImage;
    private javax.swing.JDesktopPane jDesktopPanel;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuAbrir;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private PanelImagem panelImagem;
    // End of variables declaration//GEN-END:variables

}
